public class MultipleExceptionHandlingExample {
    public static void main(String[] args) {
        try {
            // ????????? ?????????? ??????????
            generateException(1);
            generateException(2);
            generateException(3);
        } catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
            // ??? ?????????? ?????????????? ?????????
            System.out.println("??????? ???? ?? ??????????: " + e.getClass().getSimpleName());
        } catch (Ex1 e) {
            // ??? ?????? ????????? ???????? ?????????? (Ex1 <|-- Ex2 <|-- Ex3)
            System.out.println("??????? ?????????? Ex1: " + e.getClass().getSimpleName());
        }
    }

    // ????? ??? ????????? ??????????
    public static void generateException(int type) throws ArithmeticException, ArrayIndexOutOfBoundsException, Ex1, Ex2, Ex3 {
        switch (type) {
            case 1:
                throw new ArithmeticException("??????? ?? ????");
            case 2:
                throw new ArrayIndexOutOfBoundsException("????? ?? ??????? ???????");
            case 3:
                throw new Ex3("?????? ???? Ex3");
            default:
                break;
        }
    }
}

// ??????????, ?????????? ????????
class Ex1 extends Exception {
    public Ex1(String message) {
        super(message);
    }
}

class Ex2 extends Ex1 {
    public Ex2(String message) {
        super(message);
    }
}

class Ex3 extends Ex2 {
    public Ex3(String message) {
        super(message);
    }
}
